Introduction to Pandas

In [1]:
import pandas as pd

data = {
    "Name":["Pikachu","Bulbasaur","Charmander"],
    "HP":[35,45,39]
}

df = pd.DataFrame(data)

df

         Name  HP
0     Pikachu  35
1   Bulbasaur  45
2  Charmander  39

In [2]:
type(df)
df.shape
df.columns

Index(['Name', 'HP'], dtype='str')

Reading Data

In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\DELL\\Desktop\\SOC 2026\\WEEK 1\\pokemon_data.csv")

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
df.head()
df.head(10)

df.tail()

df.tail(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

Inspecting Data

In [6]:
df.info()

df.describe()

df.shape

df.columns

df.dtypes

df.index

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    str
 2   Type 1      800 non-null    str
 3   Type 2      414 non-null    str
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), str(3)
memory usage: 69.7 KB

RangeIndex(start=0, stop=800, step=1)

Selecting Data

In [7]:
df["Name"]
df[["Name","HP","Attack"]]

df.iloc[0]

df.iloc[5]

df.iloc[0:10]

df.iloc[5,2]

df.loc[0]

df.loc[0,"Name"]

'Bulbasaur'

Filtering Data

In [8]:
# Show Pokemon with HP greater than 80

df[df["HP"] > 80]

# Show Pokemon with Attack greater than 100

df[df["Attack"] > 100]

df[df["Type 1"] == "Fire"]

# Water or Grass type Pokemon

df[
    (df["Type 1"] == "Water")
    |
    (df["Type 1"] == "Grass")
]

# Check whether Type 1 belongs
# to the given list

df[
    df["Type 1"].isin(
        ["Fire","Water","Grass"]
    )
]

df[df["Attack"] > 100][
    ["Name","Attack"]
]

                          Name  Attack
7    CharizardMega Charizard X     130
8    CharizardMega Charizard Y     104
12     BlastoiseMega Blastoise     103
19       BeedrillMega Beedrill     150
39                    Nidoking     102
..                         ...     ...
793                    Yveltal     131
796        DiancieMega Diancie     160
797        HoopaHoopa Confined     110
798         HoopaHoopa Unbound     160
799                  Volcanion     110

[170 rows x 2 columns]

Sorting

In [9]:
df.sort_values("Attack")

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True

In [10]:
df.sort_values(
    "Attack",
    ascending=False
)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False

In [11]:
df.sort_values(
    ["Type 1","Attack"],
    ascending=[True,False]
)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
650,589,Escavalier,Bug,Steel,70,135,105,60,105,20,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
405,370,Luvdisc,Water,NaN,43,30,55,40,65,97,3,False
198,183,Marill,Water,Fairy,70,20,50,20,50,40,2,False
508,458,Mantyke,Water,Flying,45,20,50,60,120,50,4,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False

Adding and Removing Columns

In [12]:
df["Total"] = (
    df["HP"]
    + df["Attack"]
    + df["Defense"]
)

In [13]:
df["Attack_Percent"] = (
    df["Attack"] /
    df["Total"]
)*100

In [14]:
df.drop(
    columns=["Attack_Percent"]
)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,300
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,320
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,250
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,300
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,310

In [15]:
df.rename(
    columns={
       "HP":"Health"
    }
)

,#,Name,Type 1,Type 2,Health,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Attack_Percent
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143,34.265734
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185,33.513514
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245,33.469388
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303,33.003300
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134,38.805970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,300,33.333333
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,320,50.000000
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,250,44.000000
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,300,53.333333
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,310,35.483871

GroupBy

In [17]:
df.groupby(
   "Type 1"
).mean(
   numeric_only=True
)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Attack_Percent
Type 1,,,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,198.579710,34.415649
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,225.419355,39.523917
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,281.812500,39.670026
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,195.181818,35.439322
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,201.352941,29.503167
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,232.555556,41.461527
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,222.442308,37.911922
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,215.750000,35.132327
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,219.406250,33.449110
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,211.285714,34.304321
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,254.375000,38.212032
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,216.166667,33.708408
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,210.591837,34.679637
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,210.750000,35.460397
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,209.771930,32.759940
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,259.022727,35.411853
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,284.296296,32.532768
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,219.160714,33.465393

In [18]:
df.groupby(
   "Type 1"
).max(
   numeric_only=True
)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Attack_Percent
Type 1,,,,,,,,,,,
Bug,666,86,185,230,135,230,160,6,False,380,66.176471
Dark,717,126,150,125,140,130,125,6,True,352,54.545455
Dragon,718,125,180,130,180,150,120,6,True,395,46.964856
Electric,702,90,123,115,165,110,140,6,True,290,53.333333
Fairy,716,126,131,95,131,154,99,6,True,352,42.105263
Fighting,701,144,145,95,140,110,118,6,False,340,53.811659
Fire,721,115,160,140,159,154,126,6,True,326,50.980392
Flying,715,85,115,80,125,90,123,6,True,264,43.560606
Ghost,711,150,165,145,170,135,130,6,True,370,54.276316
Grass,673,123,132,131,145,129,145,6,True,327,48.571429
Ground,645,115,180,160,150,120,120,5,True,440,61.111111
Ice,713,110,130,184,130,200,110,6,True,396,42.857143
Normal,676,255,160,126,135,135,135,6,True,410,51.515152
Poison,691,105,106,120,100,123,130,6,False,285,43.165468
Psychic,720,190,190,160,194,160,180,6,True,396,72.000000
Rock,719,123,165,200,160,150,150,6,True,414,53.879310
Steel,707,100,150,230,150,150,110,6,True,440,57.692308
Water,693,170,155,180,180,160,122,6,True,360,58.064516

Missing Data

In [19]:
df.loc[3,"HP"] = None

In [20]:
df.isnull()

df.isnull().sum()

#                   0
Name                0
Type 1              0
Type 2            386
HP                  1
Attack              0
Defense             0
Sp. Atk             0
Sp. Def             0
Speed               0
Generation          0
Legendary           0
Total               0
Attack_Percent      0
dtype: int64

In [21]:
df.dropna()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Attack_Percent
0,1,Bulbasaur,Grass,Poison,45.0,49,49,65,65,45,1,False,143,34.265734
1,2,Ivysaur,Grass,Poison,60.0,62,63,80,80,60,1,False,185,33.513514
2,3,Venusaur,Grass,Poison,80.0,82,83,100,100,80,1,False,245,33.469388
6,6,Charizard,Fire,Flying,78.0,84,78,109,85,100,1,False,240,35.000000
7,6,CharizardMega Charizard X,Fire,Dragon,78.0,130,111,130,85,100,1,False,319,40.752351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50.0,100,150,100,150,50,6,True,300,33.333333
796,719,DiancieMega Diancie,Rock,Fairy,50.0,160,110,160,110,110,6,True,320,50.000000
797,720,HoopaHoopa Confined,Psychic,Ghost,80.0,110,60,150,130,70,6,True,250,44.000000
798,720,HoopaHoopa Unbound,Psychic,Dark,80.0,160,60,170,130,80,6,True,300,53.333333
799,721,Volcanion,Fire,Water,80.0,110,120,130,90,70,6,True,310,35.483871

In [22]:
df.fillna(0)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Attack_Percent
0,1,Bulbasaur,Grass,Poison,45.0,49,49,65,65,45,1,False,143,34.265734
1,2,Ivysaur,Grass,Poison,60.0,62,63,80,80,60,1,False,185,33.513514
2,3,Venusaur,Grass,Poison,80.0,82,83,100,100,80,1,False,245,33.469388
3,3,VenusaurMega Venusaur,Grass,Poison,0.0,100,123,122,120,80,1,False,303,33.003300
4,4,Charmander,Fire,0,39.0,52,43,60,50,65,1,False,134,38.805970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50.0,100,150,100,150,50,6,True,300,33.333333
796,719,DiancieMega Diancie,Rock,Fairy,50.0,160,110,160,110,110,6,True,320,50.000000
797,720,HoopaHoopa Confined,Psychic,Ghost,80.0,110,60,150,130,70,6,True,250,44.000000
798,720,HoopaHoopa Unbound,Psychic,Dark,80.0,160,60,170,130,80,6,True,300,53.333333
799,721,Volcanion,Fire,Water,80.0,110,120,130,90,70,6,True,310,35.483871

In [23]:
df["HP"] = df["HP"].fillna(
    df["HP"].mean()
)

Statistics

In [25]:
df["HP"].mean()

df["HP"].median()

df["HP"].max()

df["HP"].min()

df["HP"].std()

df["HP"].sum()

np.float64(55396.2453066333)

In [26]:
df[
   ["HP","Attack","Defense"]
].corr()

               HP    Attack   Defense
HP       1.000000  0.422092  0.238818
Attack   0.422092  1.000000  0.438687
Defense  0.238818  0.438687  1.000000

Combination

In [28]:
import pandas as pd

df = pd.read_csv(
   "C:\\Users\\DELL\\Desktop\\SOC 2026\\WEEK 1\\pokemon_data.csv"
)

df["Total"] = (
   df["HP"]
   + df["Attack"]
   + df["Defense"]
)

top10 = df.sort_values(
   "Total",
   ascending=False
).head(10)

print(top10[
   ["Name","Total"]
])

                        Name  Total
424    GroudonPrimal Groudon    440
333        AggronMega Aggron    440
224      SteelixMega Steelix    430
268  TyranitarMega Tyranitar    414
313                  Slaking    410
789                  Avalugg    396
163      MewtwoMega Mewtwo X    396
711       KyuremBlack Kyurem    395
494    GarchompMega Garchomp    393
423                  Groudon    390

In [29]:
top10.to_csv(
   "C:\\Users\\DELL\\Desktop\\SOC 2026\\WEEK 1\\pokemon_data.csv",
   index=False
)